package com.test.demoAssignment.entity.ticket;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "ticketFilingDb")
public class Ticket     {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String entityId;

    @DynamoDBAttribute
    private String entityType = "TICKET";

    @DynamoDBAttribute
    private String createdBy;

    @DynamoDBAttribute
    private String ticketDescription;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private Type ticketType;

    public Ticket() {}

    public Ticket(String entityId, String createdBy, String ticketDescription, Type ticketType) {
        this.entityId = entityId;
        this.createdBy = createdBy;
        this.ticketDescription = ticketDescription;
        this.ticketType = ticketType;
    }


    public Type getTicketType() {
        return ticketType;
    }

    public void setTicketType(Type ticketType) {
        this.ticketType = ticketType;
    }

    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    public String getEntityType() {
        return entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getTicketDescription() {
        return ticketDescription;
    }

    public void setTicketDescription(String ticketDescription) {
        this.ticketDescription = ticketDescription;
    }
}
