package com.test.demoAssignment.entity.user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "ticketFilingDb")
@Entity
public class User {

    @Id
    @GeneratedValue
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String entityId;

    @DynamoDBAttribute
    private String entityType = "USER";

    @NotNull
    @DynamoDBAttribute
    private String name;

    @NotNull
    @DynamoDBAttribute
    private String email;

    public User() {}

    public User(String entityId, String name, String email) {
        this.entityId = entityId;
        this.name = name;
        this.email = email;
    }

    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    public String getEntityType() {
        return entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
